# Generated by Django 4.0.1 on 2022-01-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='native_name',
            new_name='avatar',
        ),
    ]
