# Generated by Django 4.0.1 on 2022-01-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_native_name_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='location',
        ),
    ]
